import assert from 'node:assert/strict';
import {handle} from '../api-worker/index.mjs';
const now=Date.parse('2026-09-27T12:00:00Z');
const snapshot={schema_version:1,generated_at:'2026-09-27T06:00:00Z',indicators:{ON_RRP:{value:0,date:'2026-09-25',status:'ok'}}};
let reads=0;
const env={SNAPSHOT_READ_TOKEN:'test-only',MACRO_KV:{get:async()=>{reads++;return snapshot;}}};
const request=(token='test-only')=>new Request('https://example.com/api/market-snapshot',{headers:{Authorization:`Bearer ${token}`}});
globalThis.fetch=()=>{throw new Error('Unexpected external fetch');};
assert.equal((await handle(request('wrong'),env,now)).status,401);
assert.equal(reads,0);
assert.equal((await handle(request(),{},now)).status,503);
let response=await handle(request(),env,now); let body=await response.json();
assert.equal(body.rows.find(x=>x.id==='RRPONTSYD').value,0);
assert.equal(body.coverage.total,13); assert.equal(body.coverage.usable,1);
assert.equal(body.rows.find(x=>x.id==='DFII10').status,'missing');
body=await (await handle(request(),env,now+3*86400000)).json();
assert.equal(body.coverage.usable,0);
assert.equal(body.rows.find(x=>x.id==='RRPONTSYD').status,'stale');
assert.equal((await handle(request(),{...env,MACRO_KV:{get:async()=>null}},now)).status,503);
assert.equal((await handle(request(),{...env,MACRO_KV:{get:async()=>{throw Error('private');}}},now)).status,503);
console.log('API Worker auth, zero, missing, stale, and no-upstream checks passed');
